/**
 * songs.js
 *
 * The app's songs
 */

window.songs = [
  /* TODO */
  {
  songID: "SID-101",
  artistID: "AID-115",
  songName: "God's Plan",
  yearReleased: "2018",
  duration: "334",
  url: "https://www.youtube.com/watch?v=xpVfcZ0ZcFM",
  explicit: true,
  },
  {
    songID: "SID-102",
    artistID: "AID-115",
    songName: "You Broke My Heart",
    yearReleased: "2023",
    duration: "293",
    url: "https://www.youtube.com/watch?v=w1-jss2mZlY",
    explicit: true,
    },
    {
    songID: "SID-103",
    artistID: "AID-115",
    songName: "Polar opposites",
    yearReleased: "2023",
    duration: "252",
    url: "https://www.youtube.com/watch?v=0bxhAxRmrJw",
    explicit: true,
    },
    {
      songID: "SID-104",
      artistID: "AID-115",
      songName: "Search & Rescue",
      yearReleased: "2023",
      duration: "273",
      url: "https://www.youtube.com/watch?v=ntp9_iznQ-0",
      explicit: true,
      },
      {
        songID: "SID-105",
        artistID: "AID-115",
        songName: "Jumbotron Shit Poppin",
        yearReleased: "2023",
        duration: "142",
        url: "https://www.youtube.com/watch?v=Iu9xmEaHwpU",
        explicit: true,
        },
        {
          songID: "SID-106",
          artistID: "AID-115",
          songName: "Jimmy Cooks",
          yearReleased: "2023",
          duration: "171",
          url: "https://www.youtube.com/watch?v=4nyld2SqleU",
          explicit: true,
          },
          {
            songID: "SID-107",
            artistID: "AID-115",
            songName: "Laugh now cry later",
            yearReleased: "2020",
            duration: "301",
            url: "https://www.youtube.com/watch?v=JFm7YDVlqnI",
            explicit: true,
            },
            {
              songID: "SID-108",
              artistID: "AID-115",
              songName: "Toosie Slide",
              yearReleased: "2020",
              duration: "248",
              url: "https://www.youtube.com/watch?v=dGYxT1QReQs",
              explicit: true,
              },
              {
                songID: "SID-201",
                artistID: "AID-211",
                songName: "Popular",
                yearReleased: "2024",
                duration: "230",
                url: "https://www.youtube.com/watch?v=vt0i6nuqNEo",
                explicit: false,
                },
                {
                  songID: "SID-202",
                  artistID: "AID-211",
                  songName: "Creepin",
                  yearReleased: "2023",
                  duration: "232",
                  url: "https://www.youtube.com/watch?v=_qPtl2w75K4",
                  explicit: true,
                  },
                  {
                    songID: "SID-203",
                    artistID: "AID-211",
                    songName: "All i know",
                    yearReleased: "2023",
                    duration: "321",
                    url: "https://www.youtube.com/watch?v=4iSEJB1KJ0w",
                    explicit: true,
                    },
                    {
                      songID: "SID-204",
                      artistID: "AID-211",
                      songName: "Reminder",
                      yearReleased: "2023",
                      duration: "219",
                      url: "https://www.youtube.com/watch?v=h_VCgsWLmY4",
                      explicit: true,
                      },
                      {
                        songID: "SID-205",
                        artistID: "AID-211",
                        songName: "Attention",
                        yearReleased: "2023",
                        duration: "197",
                        url: "https://www.youtube.com/watch?v=3tHuJAZpYNw",
                        explicit: false,
                        },
                        {
                          songID: "SID-206",
                          artistID: "AID-211",
                          songName: "Ordinary life",
                          yearReleased: "2023",
                          duration: "222",
                          url: "https://www.youtube.com/watch?v=PlJV9IesfIk",
                          explicit: true,
                          },
                          {
                            songID: "SID-207",
                            artistID: "AID-211",
                            songName: "Secrets",
                            yearReleased: "2023",
                            duration: "265",
                            url: "https://www.youtube.com/watch?v=nh3Nc2XsdM0",
                            explicit: false,
                            },
                            {
                              songID: "SID-301",
                              artistID: "AID-323",
                              songName: "I Know",
                              yearReleased: "2024",
                              duration: "226",
                              url: "https://www.youtube.com/watch?v=X7aF3nZOS98",
                              explicit: true,
                              },
                              {
                                songID: "SID-302",
                                artistID: "AID-323",
                                songName: "HYAENA",
                                yearReleased: "2023",
                                duration: "176",
                                url: "https://www.youtube.com/watch?v=eUdmON7OPXM",
                                explicit: true,
                                },
                                {
                                  songID: "SID-303",
                                  artistID: "AID-323",
                                  songName: " Sirens",
                                  yearReleased: "2023",
                                  duration: "199",
                                  url: "https://www.youtube.com/watch?v=6gUiQ8CqLcY",
                                  explicit: true,
                                  },
                                  {
                                    songID: "SID-304",
                                    artistID: "AID-323",
                                    songName: "TELEKINESIS",
                                    yearReleased: "2023",
                                    duration: "355",
                                    url: "https://www.youtube.com/watch?v=xl5LunV-OkU",
                                    explicit: true,
                                    },
                                    {
                                      songID: "SID-305",
                                      artistID: "AID-323",
                                      songName: "FE!N",
                                      yearReleased: "2023",
                                      duration: "193",
                                      url: "https://www.youtube.com/watch?v=U-l4ya3ejko",
                                      explicit: true,
                                      },
                                                                              
                                          

];
